name: Main

on:
  push:
    branches:
      - main

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'

    steps:      
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set variables
          id: variables
          run: |
            message=$(git log -1 --pretty=%s | sed "s/['\"\`]//g")
            echo "setting updateeeee message to $message"
            echo "update_message=$message" >> $GITHUB_OUTPUT

        - name: output variables
          run: |
            echo "variables are set to:"
            echo "update_message : ${{ steps.variables.outputs.update_message }}"
